=== voltron42/sandbox/jurassic/xml/grammar.dtd
<!ELEMENT glossary (tag*, (plan | thing), thing*)>
<!ATTLIST glossary name CDATA #REQUIRED>
<!ELEMENT tag EMPTY>
<!ATTLIST tag glossary CDATA #REQUIRED>
<!ELEMENT thing (of, series?, has*)>
<!ELEMENT of (of*, is?)>
<!ATTLIST of type CDATA #REQUIRED>
<!ELEMENT is (of+)>
<!ELEMENT series (member+)>
<!ELEMENT member (with*)>
<!ATTLIST member name CDATA #REQUIRED>
<!ELEMENT has ((of,(simple|act)?)|plan)>
<!ATTLIST has name CDATA #REQUIRED>
<!ATTLIST has use (me|glossary|family|all) #REQUIRED>
<!ATTLIST has access (thing|type) #REQUIRED>
<!ATTLIST has change (can|cannot) #REQUIRED>
<!ELEMENT simple EMPTY>
<!ATTLIST simple value CDATA #REQUIRED>
<!ELEMENT act (to, do, with*)>
<!ELEMENT do (simple|act|plan)>
<!ELEMENT to (simple|act|plan)>
<!ELEMENT with (simple|act|plan)>
<!ATTLIST with name CDATA #REQUIRED>
<!ELEMENT plan (of*, parts?, (steps | native)?)>
<!ELEMENT parts ((give|take), take*)>
<!ELEMENT give (of, default?)>
<!ELEMENT take (of, default?)>
<!ATTLIST take name CDATA #REQUIRED>
<!ELEMENT default (simple|act|plan)>
<!ELEMENT steps (act*, (act|return))>
<!ELEMENT return (simple|act|plan)>
<!ELEMENT native EMPTY>

=== voltron42/sandbox/jurassic/xml/Jurassic_Geo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossary SYSTEM "grammar.dtd">
<glossary name="Jurassic Geo">
  <tag glossary="Jurassic"/>
  <thing>
    <of type="Canvas">
      <is>
        <of type="Panel"/>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Shape"/>
    <has name="draw" use="family" access="thing" change="can">
      <plan>
      </plan>
    </has>
  </thing>
</glossary>

=== voltron42/sandbox/jurassic/xml/Jurassic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossary SYSTEM "grammar.dtd">
<glossary name="Jurassic">
  <thing>
    <of type="Thing"/>
    <has name="$" use="all" access="thing" change="can">
      <!--
      '$' denotes the current type
      Since all types extend 'Thing', 
      then this method will share the name of the type 
      implementing it as well as it's return type.
      -->
      <plan>
        <parts>
          <give>
            <of type="$"/>
          </give>
          <take name="pieces">
            <of type="Lookup"/>
          </take>
          <take name="inner">
            <of type="List"/>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="getType" use="all" access="thing" change="cannot">
      <plan>
        <parts>
          <give>
            <of type="Type"/>
          </give>
        </parts>
        <native/>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Nothing">
      <is>
        <of type="Thing"/>
      </is>
    </of>
    <has name="INSTANCE" use="all" access="type" change="cannot">
      <of type="?"/>
    </has>
  </thing>
  <thing>
    <of type="Boolean">
      <is>
        <of type="Thing"/>
      </is>
    </of>
    <series>
      <member name="TRUE"/>
      <member name="FALSE"/>
    </series>
    <has name="asText" use="all" access="thing" change="cannot">
      <plan>
        <native/>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Text">
      <is>
        <of type="Thing"/>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Number">
      <is>
        <of type="Thing"/>
      </is>
    </of>
    <has name="asInteger" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="Integer"/>
          </give>
        </parts>
      </plan>
    </has>
    <has name="asDecimal" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="Decimal"/>
          </give>
        </parts>
      </plan>
    </has>
    <has name="asFraction" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="Fraction"/>
          </give>
        </parts>
      </plan>
    </has>
    <has name="asText" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="Text"/>
          </give>
        </parts>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Integer">
      <is>
        <of type="Thing"/>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Decimal">
      <is>
        <of type="Thing"/>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Fraction">
      <is>
        <of type="Thing"/>
      </is>
    </of>
    <has name="numerator" access="thing" use="all" change="cannot">
      <of type="Integer"/>
    </has>
    <has name="denominator" access="thing" use="all" change="cannot">
      <of type="Integer"/>
    </has>
  </thing>
  <thing>
    <of type="Walker">
      <of type="#1"/>
    </of>
    <has name="step" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="#1"/>
          </give>
        </parts>
      </plan>
    </has>
    <has name="canStep" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="Boolean"/>
          </give>
        </parts>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Walkable">
      <of type="#1"/>
    </of>
    <has name="getWalker" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="Walker">
              <of type="#1"/>
            </of>
          </give>
        </parts>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Range">
      <of type="#1">
        <is>
          <of type="Number"/>
        </is>
      </of>
      <is>
        <of type="Walkable">
          <of type="#1"/>
        </of>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Group">
      <of type="#1"/>
      <is>
        <of type="Walkable">
          <of type="#1"/>
        </of>
      </is>
    </of>
    <has name="add" use="all" access="thing" change="can">
      <plan>
        <parts>
          <take name="element">
            <of type="#1"/>
          </take>
        </parts>
      </plan>
    </has>
    <has name="remove" use="all" access="thing" change="can">
      <plan>
        <parts>
          <take name="element">
            <of type="#1"/>
          </take>
        </parts>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Set">
      <of type="#1"/>
      <is>
        <of type="Group">
          <of type="#1"/>
        </of>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Index">
      <of type="#1"/>
      <of type="#2">
        <is>
          <of type="Walkable">
            <of type="#1"/>
          </of>
        </is>
      </of>
      <of type="#3"/>
      <is>
        <of type="Walkable">
          <of type="#1"/>
        </of>
      </is>
    </of>
    <has name="get" use="all" access="thing" change="can">
      <plan>
        <parts>
          <give>
            <of type="#3"/>
          </give>
          <take name="key">
            <of type="#1"/>
          </take>
        </parts>
      </plan>
    </has>
    <has name="set" use="all" access="thing" change="can">
      <plan>
        <parts>
          <take name="key">
            <of type="#1"/>
          </take>
          <take name="value">
            <of type="#3"/>
          </take>
        </parts>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="List">
      <of type="#1"/>
      <is>
        <of type="Index">
          <of type="Integer"/>
          <of type="Range">
            <of type="Integer"/>
          </of>
          <of type="#1"/>
        </of>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Lookup">
      <of type="#1"/>
      <is>
        <of type="Index">
          <of type="String"/>
          <of type="Set">
            <of type="String"/>
          </of>
          <of type="#1"/>
        </of>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Action">
      <of type="*"/>
      <is>
        <of type="Thing"/>
      </is>
    </of>
  </thing>
  <thing>
    <of type="Type">
      <of type="#1"/>
      <is>
        <of type="Thing"/>
      </is>
    </of>
    <has name="getName" use="all" access="thing" change="cannot">
      <plan>
        <parts>
          <give>
            <of type="Text"/>
          </give>
        </parts>
      </plan>
    </has>
    <has name="getInnerTypeCount" use="family" access="thing" change="cannot">
      <plan>
        <parts>
          <give>
            <of type="Integer"/>
          </give>
        </parts>
      </plan>
    </has>
    <has name="getInnerTypes" use="family" access="thing" change="cannot">
      <plan>
        <parts>
          <give>
            <of type="List">
              <of type="Type"/>
            </of>
          </give>
        </parts>
      </plan>
    </has>
    <has name="getInnerTypes" use="family" access="thing" change="cannot">
      <plan>
        <parts>
          <give>
            <of type="List">
              <of type="Text"/>
            </of>
          </give>
        </parts>
      </plan>
    </has>
  </thing>
</glossary>

=== voltron42/sandbox/jurassic/xml/Hello_World.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossary SYSTEM "grammar.dtd">
<glossary name="Hello World">
  <tag glossary="Jurassic Base"/>
  <plan>
    <steps>
      <act>
        <to>
          <simple value="window"/>
        </to>
        <do>
          <simple value="write"/>
        </do>
        <with name="text">
          <simple value="Hello World!"/>
        </with>
      </act>
    </steps>
  </plan>
</glossary>

=== voltron42/sandbox/jurassic/xml/Jurassic_Base.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossary SYSTEM "grammar.dtd">
<glossary name="Jurassic Base">
  <tag glossary="Jurassic"/>
  <tag glossary="Jurassic Window"/>
  <thing>
    <of type="Jurassic"/>
    <has name="window" use="all" access="type" change="cannot">
      <of type="Window"/>
    </has>
    <has name="walk" use="all" access="type" change="cannot">
      <plan>
        <of type="#1"/>
        <parts>
          <take name="span">
            <of type="Walkable">
              <of type="#1"/>
            </of>
          </take>
          <take name="callback">
            <of type="Action">
              <of type="Boolean"/>
              <of type="#1"/>
            </of>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="filterGroup" use="all" access="type" change="cannot">
      <plan>
        <of type="#1"/>
        <of type="#2">
          <is>
            <of type="Group">
              <of type="#1"/>
            </of>
          </is>
        </of>
        <parts>
          <give>
            <of type="#2"/>
          </give>
          <take name="span">
            <of type="#2"/>
          </take>
          <take name="callback">
            <of type="Action">
              <of type="Boolean"/>
              <of type="#1"/>
            </of>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="filterIndex" use="all" access="type" change="cannot">
      <plan>
        <of type="#1"/>
        <of type="#2"/>
        <of type="#3"/>
        <of type="#4">
          <is>
            <of type="Index">
              <of type="#1"/>
              <of type="#2">
                <is>
                  <of type="Walkable">
                    <of type="#1"/>
                  </of>
                </is>
              </of>
              <of type="#3"/>
            </of>
          </is>
        </of>
        <parts>
          <give>
            <of type="#4"/>
          </give>
          <take name="span">
            <of type="#4"/>
          </take>
          <take name="callback">
            <of type="Action">
              <of type="Boolean"/>
              <of type="#1"/>
              <of type="#3"/>
            </of>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="mapGroup" use="all" access="type" change="cannot">
      <plan>
        <of type="#1"/>
        <of type="#2">
          <is>
            <of type="Group">
              <of type="#1"/>
            </of>
          </is>
        </of>
        <of type="#3"/>
        <of type="#4">
          <is>
            <of type="Group">
              <of type="#3"/>
            </of>
          </is>
        </of>
        <parts>
          <give>
            <of type="#4"/>
          </give>
          <take name="span">
            <of type="#2"/>
          </take>
          <take name="callback">
            <of type="Action">
              <of type="#3"/>
              <of type="#1"/>
            </of>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="filterIndex" use="all" access="type" change="cannot">
      <plan>
        <of type="#1"/>
        <of type="#2"/>
        <of type="#3"/>
        <of type="#4">
          <is>
            <of type="Index">
              <of type="#1"/>
              <of type="#2">
                <is>
                  <of type="Walkable">
                    <of type="#1"/>
                  </of>
                </is>
              </of>
              <of type="#3"/>
            </of>
          </is>
        </of>
        <of type="#5"/>
        <of type="#6">
          <is>
            <of type="Index">
              <of type="#1"/>
              <of type="#2">
                <is>
                  <of type="Walkable">
                    <of type="#1"/>
                  </of>
                </is>
              </of>
              <of type="#5"/>
            </of>
          </is>
        </of>
        <parts>
          <give>
            <of type="#5"/>
          </give>
          <take name="span">
            <of type="#4"/>
          </take>
          <take name="callback">
            <of type="Action">
              <of type="#5"/>
              <of type="#1"/>
              <of type="#3"/>
            </of>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="if else"  use="all" access="type" change="cannot">
      <plan>
        <parts>
          <take name="condition">
            <of type="Action">
              <of type="Boolean"/>
            </of>
          </take>
          <take name="when true">
            <of type="Action"/>
          </take>
          <take name="when false">
            <of type="Action"/>
          </take>
        </parts>
        <native/>
      </plan>
    </has> 
  </thing>
  <thing>
    <of type="Math"/>
  </thing>
</glossary>

=== voltron42/sandbox/jurassic/xml/Jurassic_Window.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glossary SYSTEM "grammar.dtd">
<glossary name="Jurassic Window">
  <tag glossary="Jurassic"/>
  <thing>
    <of type="Panel">
      <of type="Thing"/>
    </of>
    <has name="write" use="all" access="thing" change="can">
      <plan>
        <parts>
          <take name="statement">
            <of type="Text"/>
          </take>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="getX" use="all" access="type" change="can">
      <plan>
        <parts>
          <give>
            <of type="Integer"/>
          </give>
        </parts>
        <native/>
      </plan>
    </has>
    <has name="getY" use="all" access="type" change="can">
      <plan>
        <parts>
          <give>
            <of type="Integer"/>
          </give>
        </parts>
        <native/>
      </plan>
    </has>
  </thing>
  <thing>
    <of type="Window">
      <is>
        <of type="Panel"/>
      </is>
    </of>
  </thing>
</glossary>
