=== voltron42/sandbox/umlsvg/domain.dtd
<!ELEMENT uml (domain|sequence)>
<!ELEMENT domain ((interface|class),(interface|class|enum|relationship)*)>
<!ELEMENT interface (extends*,constant*,method-declaration*)>
<!ATTLIST interface
  name CDATA #REQUIRED
>
<!ELEMENT extends EMPTY>
<!ATTLIST extends interface CDATA #REQUIRED>
<!ELEMENT constant (variable)>
<!ELEMENT variable (primitive|datatype)>
<!ATTLIST variable name CDATA #REQUIRED>
<!ELEMENT primitive EMPTY>
<!ATTLIST primitive type (boolean|integer|decimal|string|date|regexp) #REQUIRED>
<!ELEMENT datatype EMPTY>
<!ATTLIST datatype 
  name CDATA #REQUIRED
>
<!ELEMENT method-declaration (return-type, parameter*)>
<!ATTLIST method-declaration
  name CDATA #REQUIRED
>
<!ELEMENT parameter (variable)>
<!ELEMENT return-type (primitive|datatype)>
<!ELEMENT class (implements*,field*,method*,constructor*)>
<!ATTLIST class 
  name CDATA #REQUIRED
  extends CDATA #IMPLIED
  is-abstract (true|false) #IMPLIED
>
<!ELEMENT implements EMPTY>
<!ATTLIST implements interface CDATA #REQUIRED>
<!ELEMENT field (variable,access)>
<!ATTLIST field 
  include-getter (true|false) #IMPLIED
  include-setter (true|false) #IMPLIED
>
<!ELEMENT access EMPTY>
<!ATTLIST access 
  visibility (public|protected|private) #IMPLIED
  is-static (true|false) #IMPLIED
  is-final (true|false) #IMPLIED
>
<!ELEMENT method (method-declaration,(access|abstract-access))>
<!ELEMENT abstract-access EMPTY>
<!ATTLIST abstract-access 
  visibility (public|protected) #IMPLIED
>
<!ELEMENT constructor (parameter*)>
<!ELEMENT enum (enum-value*)>
<!ATTLIST enum 
  name CDATA #REQUIRED
>
<!ELEMENT enum-value EMPTY>
<!ATTLIST enum-value
  value CDATA #REQUIRED
>
<!ELEMENT relationship (from,to)>
<!ATTLIST relationship
  name CDATA #REQUIRED
>
<!ELEMENT from (node)>
<!ELEMENT to (node)>
<!ELEMENT node EMPTY>
<!ATTLIST node
  className CDATA #REQUIRED
  cardinality (optional|required|zeroOrMore|oneOrMore) #IMPLIED
>
<!ELEMENT sequence EMPTY>

=== voltron42/sandbox/umlsvg/gameplandomain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE uml SYSTEM "domain.dtd">
<uml>
  <domain>
    <class name="Game">
      <field include-getter="true" include-setter="false">
        <variable name="title">
          <primitive type="string"/>
        </variable>
        <access is-final="false" is-static="false" visibility="private"/>
      </field>
    </class>
    <class name="Board">
    </class>
    <class name="Space">
    </class>
    <class name="Deck">
    </class>
    <class name="Card">
    </class>
    <relationship name="gameBoards">
      <from>
        <node className="Game" cardinality="required"/>
      </from>
      <to>
        <node className="Board" cardinality="zeroOrMore"/>
      </to>
    </relationship>
    <relationship name="spaces">
      <from>
        <node className="Board" cardinality="required"/>
      </from>
      <to>
        <node className="Space" cardinality="oneOrMore"/>
      </to>
    </relationship>
    <relationship name="gameDecks">
      <from>
        <node className="Game" cardinality="required"/>
      </from>
      <to>
        <node className="Deck" cardinality="zeroOrMore"/>
      </to>
    </relationship>
    <relationship name="cards">
      <from>
        <node className="Deck" cardinality="required"/>
      </from>
      <to>
        <node className="Card" cardinality="oneOrMore"/>
      </to>
    </relationship>
  </domain>
</uml>
